"""initial migration

Revision ID: 956ba9fcd1e0
Revises: 
Create Date: 2026-09-30 19:40:22.773196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956ba9fcd1e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('flat_number', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('resident', 'partner', 'admin', 'super_admin', name='userrole', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'suspended', 'blocked', 'deactivated', name='userstatus', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_flat_number'), 'users', ['flat_number'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'placed', 'accepted', 'rejected', 'preparing', 'ready', 'dispatched', 'in_transit', 'delivered', 'cancelled', 'refund_pending', 'refunded', name='orderstatus', create_constraint=True), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_preorder', sa.Boolean(), nullable=False),
    sa.Column('delivery_slot', sa.String(length=50), nullable=True),
    sa.Column('target_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_type', sa.Enum('doorstep', 'self_pickup', name='deliverytype', create_constraint=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_partner_id'), 'orders', ['partner_id'], unique=False)
    op.create_index(op.f('ix_orders_resident_id'), 'orders', ['resident_id'], unique=False)
    op.create_table('partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.String(length=255), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('upi_account_name', sa.String(length=255), nullable=True),
    sa.Column('is_upi_verified', sa.Boolean(), nullable=False),
    sa.Column('free_orders_remaining', sa.Integer(), nullable=False),
    sa.Column('maintenance_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lifetime_orders_count', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=False),
    sa.Column('punctuality_rating', sa.Float(), nullable=False),
    sa.Column('avg_delivery_minutes', sa.Integer(), nullable=False),
    sa.Column('total_orders_completed', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('application_status', sa.Enum('draft', 'pending', 'under_review', 'approved', 'rejected', 'withdrawn', name='approvalstatus', create_constraint=True), nullable=False),
    sa.Column('partner_status', sa.Enum('pending', 'active', 'suspended', 'blocked', 'inactive', name='partnerstatus', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', name='payoutstatus', create_constraint=True), nullable=False),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payout_id', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_index(op.f('ix_payouts_partner_id'), 'payouts', ['partner_id'], unique=False)
    op.create_index(op.f('ix_payouts_provider_payout_id'), 'payouts', ['provider_payout_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_required', 'pending', 'dispatched', 'in_transit', 'delivered', 'failed', 'returned', name='deliverystatus', create_constraint=True), nullable=False),
    sa.Column('partner_flat', sa.String(length=50), nullable=True),
    sa.Column('resident_flat', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=True)
    op.create_index(op.f('ix_deliveries_partner_id'), 'deliveries', ['partner_id'], unique=False)
    op.create_index(op.f('ix_deliveries_resident_id'), 'deliveries', ['resident_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('veg', 'non_veg', 'snacks', 'desserts', 'beverages', 'other', name='menucategory', create_constraint=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('spice_level', sa.String(length=50), nullable=True),
    sa.Column('is_preorder_only', sa.Boolean(), nullable=False),
    sa.Column('preorder_cutoff_time', sa.String(length=10), nullable=True),
    sa.Column('available_slots', sa.JSON(), nullable=True),
    sa.Column('max_batch_quantity', sa.Integer(), nullable=False),
    sa.Column('min_lead_time_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_partner_id'), 'menus', ['partner_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'pending', 'authorized', 'captured', 'failed', 'cancelled', 'refund_pending', 'refunded', 'partially_refunded', name='paymentstatus', create_constraint=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('provider_signature', sa.String(length=255), nullable=True),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('partner_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_partner_id'), 'payments', ['partner_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_resident_id'), 'payments', ['resident_id'], unique=False)
    op.create_index(op.f('ix_payments_utr_number'), 'payments', ['utr_number'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_profiles.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_order_id'), 'ratings', ['order_id'], unique=True)
    op.create_index(op.f('ix_ratings_partner_id'), 'ratings', ['partner_id'], unique=False)
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_table('dish_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('veg', 'non_veg', 'snacks', 'desserts', 'beverages', 'other', name='menucategory', create_constraint=True), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed_by_chef', 'fulfilled', 'closed', name='suggestionstatus', create_constraint=True), nullable=False),
    sa.Column('accepted_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('created_menu_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_partner_id'], ['partner_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_suggestions_accepted_by_partner_id'), 'dish_suggestions', ['accepted_by_partner_id'], unique=False)
    op.create_index(op.f('ix_dish_suggestions_id'), 'dish_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_dish_suggestions_user_id'), 'dish_suggestions', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.Enum('credit', 'debit', 'platform_fee', 'maintenance_fee', 'maintenance_recharge', 'refund', name='ledgerentrytype', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_order_id'), 'ledger_entries', ['order_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_payment_id'), 'ledger_entries', ['payment_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('dish_upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['dish_suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'suggestion_id', name='uq_user_dish_suggestion')
    )
    op.create_index(op.f('ix_dish_upvotes_id'), 'dish_upvotes', ['id'], unique=False)
    op.create_index(op.f('ix_dish_upvotes_suggestion_id'), 'dish_upvotes', ['suggestion_id'], unique=False)
    op.create_index(op.f('ix_dish_upvotes_user_id'), 'dish_upvotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_upvotes_user_id'), table_name='dish_upvotes')
    op.drop_index(op.f('ix_dish_upvotes_suggestion_id'), table_name='dish_upvotes')
    op.drop_index(op.f('ix_dish_upvotes_id'), table_name='dish_upvotes')
    op.drop_table('dish_upvotes')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_payment_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_order_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_dish_suggestions_user_id'), table_name='dish_suggestions')
    op.drop_index(op.f('ix_dish_suggestions_id'), table_name='dish_suggestions')
    op.drop_index(op.f('ix_dish_suggestions_accepted_by_partner_id'), table_name='dish_suggestions')
    op.drop_table('dish_suggestions')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_partner_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_order_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_payments_utr_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_resident_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_partner_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_menus_partner_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_deliveries_resident_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_partner_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_payouts_provider_payout_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_partner_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('partner_profiles')
    op.drop_index(op.f('ix_orders_resident_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_partner_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_flat_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
