"""add_delivery_and_seller_is_open

Revision ID: c373aa388bf0
Revises: fb761036c8a7
Create Date: 2026-08-20 18:26:15.358277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c373aa388bf0"
down_revision: Union[str, Sequence[str], None] = "fb761036c8a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "dispatched",
                "delivered",
                "failed",
                name="deliverystatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("seller_flat", sa.String(length=50), nullable=True),
        sa.Column("buyer_flat", sa.String(length=50), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deliveries_buyer_id"), "deliveries", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_deliveries_id"), "deliveries", ["id"], unique=False)
    op.create_index(op.f("ix_deliveries_order_id"), "deliveries", ["order_id"], unique=True)
    op.create_index(op.f("ix_deliveries_seller_id"), "deliveries", ["seller_id"], unique=False)
    op.add_column(
        "seller_profiles",
        sa.Column("is_open", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller_profiles", "is_open")
    op.drop_index(op.f("ix_deliveries_seller_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_order_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_buyer_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS deliverystatus")
